# Generated by Django 5.2.16 on 2026-08-16 14:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
            ],
            options={
                'verbose_name_plural': 'participants',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrolled_at', models.DateTimeField(auto_now=True)),
                ('activity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activity')),
                ('participant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.participant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('activity_id', 'participant_id'), name='unique_enrollment_activity_participant')],
            },
        ),
    ]
