# Generated by Django 5.2.16 on 2026-08-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_participant_enrollment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_enrollment_activity_participant',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='activity_id',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='participant_id',
            new_name='participant',
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('activity', 'participant'), name='unique_enrollment_activity_participant'),
        ),
    ]
